# Generated by Django 6.0.4 on 2026-04-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='found_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lost_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
