# Generated by Django 6.0.4 on 2026-04-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recover', '0003_item_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
